# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('PublishedDate_Post', models.DateTimeField(auto_now_add=True)),
                ('Worker', models.TextField(max_length=100)),
                ('Status', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=100)),
                ('PublishedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Project_NameUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageYourself.Projects')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Project_NamePost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageYourself.Projects'),
        ),
    ]
