# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-29 16:12
from __future__ import unicode_literals

import ManageYourself.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageYourself', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='Status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Worker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='Project_NameUser',
            field=models.ForeignKey(on_delete=ManageYourself.models.Projects, to='ManageYourself.Projects'),
        ),
    ]
